name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true cygnetops/react-test npm test

      - name: Set Identity Provider
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/692227404432/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'multi-k8-deployer@multi-k8s-398620.iam.gserviceaccount.com'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-398620

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-east1-b

      - name: Build
        run: |-
          docker build -t cdavey306/multi-client-k8s-gh:latest -t cdavey306/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t cdavey306/multi-server-k8s-pgfix-gh:latest -t cdavey306/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t cdavey306/multi-worker-k8s-gh:latest -t cdavey306/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push cdavey306/multi-client-k8s-gh:latest
          docker push cdavey306/multi-server-k8s-pgfix-gh:latest
          docker push cdavey306/multi-worker-k8s-gh:latest

          docker push cdavey306/multi-client-k8s-gh:${{ env.SHA }}
          docker push cdavey306/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          docker push cdavey306/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=cdavey306/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=cdavey306/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=cdavey306/multi-worker-k8s-gh:${{ env.SHA }}
